version: '3.1'

services:

  database:
    container_name: addressbook-database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: addressbook
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
